/**
 * Sim runner — writes the matrix output to docs/sim-findings/rogue-balance.md.
 * Not a real test in the validation sense: the engine integration tests cover
 * correctness. This file exists because vitest is the only TS runner wired up
 * in this repo, and using it lets us re-run the sim with `npm run test:run --
 * src/sim/rogueSim.test.ts`.
 */
import { describe, it, expect } from 'vitest';
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { runMatrix, formatSummary, type MatrixSummary, type SimVariant } from './rogueSim';

const OUT_DIR = resolve(process.cwd(), 'docs/sim-findings');
const OUT_FILE = resolve(OUT_DIR, 'rogue-balance.md');

const START_LEVELS = [1, 3, 5, 7];
const VARIANTS: SimVariant[] = ['vanilla', 'loaded'];
const RUNS_PER_CELL = 50;

describe('Rogue balance matrix', () => {
  it('runs 50× per {L1,L3,L5,L7} × {vanilla,loaded} and writes findings', () => {
    const startedAt = Date.now();
    const { summaries } = runMatrix(START_LEVELS, VARIANTS, RUNS_PER_CELL);
    const elapsedSec = ((Date.now() - startedAt) / 1000).toFixed(1);

    const headline = headlineSection(summaries);
    const perCell = summaries.map(formatSummary).join('\n\n');

    const md = renderReport({ headline, perCell, elapsedSec, runs: RUNS_PER_CELL });
    mkdirSync(OUT_DIR, { recursive: true });
    writeFileSync(OUT_FILE, md, 'utf8');

    // eslint-disable-next-line no-console
    console.log(`\n[rogueSim] wrote ${OUT_FILE} (${elapsedSec}s)\n${headline}`);

    // ── Guard-rails (re-tightened 2026-05-30 to the 6-chapter reality) ──────
    // Bands now snug around the current full-resim numbers (full-resim lane):
    // the bare/loaded rogue clears 0% of the 6-chapter run at the AI floor, so
    // every cell dies 100% and avg depth tops out ~25 rooms / ~1.8 chapters.
    // Caps are set to the true 6-chapter ceiling (a routed clear is ~62-66
    // rooms / 6 chapters) so a counting bug or a content-size change trips
    // them, while leaving slack for legitimate balance drift.
    expect(summaries.length).toBe(START_LEVELS.length * VARIANTS.length);
    for (const s of summaries) {
      expect(s.runs).toBe(RUNS_PER_CELL);
      expect(s.avgRoomsCleared).toBeGreaterThan(0);
      expect(s.avgRoomsCleared).toBeLessThanOrEqual(70); // routed clear ≈ 66 rooms
      expect(s.deathRate).toBeGreaterThanOrEqual(0);
      expect(s.deathRate).toBeLessThanOrEqual(1);
      expect(s.avgChaptersCleared).toBeGreaterThanOrEqual(0);
      expect(s.avgChaptersCleared).toBeLessThanOrEqual(6); // 6-chapter run
    }

    // Anti-immortal floor: every cell must still die the large majority of the
    // time. The class-balance-philosophy floor is "each death is rewarding",
    // and this sim exists because of the "feels immortal" rogue report. Every
    // cell sits at 100% death today (the 6-chapter run out-runs the bare/loaded
    // AI-floor rogue), so the > 0.6 band leaves wide room for a real
    // survivability buff while still going RED if the rogue turns near-
    // unkillable (the regression this guards against).
    const minDeathRate = Math.min(...summaries.map((s) => s.deathRate));
    expect(minDeathRate).toBeGreaterThan(0.6);
  }, 600_000);
});

function headlineSection(summaries: MatrixSummary[]): string {
  const lines: string[] = [];
  lines.push('| Variant | L | Death% | Avg ch | Avg rooms | Avg dmg dealt | Avg dmg taken | Temp HP | HP Δ/enc | Sneaks | Hide% |');
  lines.push('|---------|---|--------|--------|-----------|---------------|---------------|---------|----------|--------|-------|');
  for (const s of summaries) {
    lines.push(
      `| ${s.variant} | ${s.startLevel} | ${(s.deathRate * 100).toFixed(0)}% | ${s.avgChaptersCleared.toFixed(2)} | ${s.avgRoomsCleared.toFixed(1)} | ${s.avgDamageDealt.toFixed(1)} | ${s.avgDamageTaken.toFixed(1)} | ${s.avgHpHealedTemp.toFixed(1)} | ${s.avgHpDeltaPerEncounter.toFixed(2)} | ${s.avgSneakAttacks.toFixed(1)} | ${(s.cunningHidePct * 100).toFixed(0)}% |`,
    );
  }
  return lines.join('\n');
}

function renderReport(opts: { headline: string; perCell: string; elapsedSec: string; runs: number }): string {
  return `# Rogue Balance Findings (2026-05-27)

_Auto-generated by \`src/sim/rogueSim.test.ts\`. Re-run with \`npm run test:run -- src/sim/rogueSim.test.ts\`. Wall clock: ${opts.elapsedSec}s for the full matrix._

## Setup

- **Class:** Rogue (Wood Elf, DEX 14 base / 16 effective, CON 14, rapier + leather armor)
- **Delve:** \`createGodwakeDelve\` (full procedural run: 6 chapters + 5 camps + 6 boss rooms)
- **Variants:**
  - **vanilla** — bare soul, no shrine pickups (floor reference).
  - **loaded** — defensively-optimal blessing pick at each of the 8 shrines: weights \`extraTempHpPerRoom\` (renewable HP) > AC > damage > first-strike tricks.
- **AI policy:**
  - Bonus action → Cunning Action: Hide for advantage (triggers Sneak Attack).
  - Disengage instead if HP < 30%.
  - Attack the lowest-HP alive monster with main-hand weapon.
  - Quaff a healing potion if HP ≤ 35% and one is in inventory.
  - Camp choice = rest (longRest).
  - Rest rooms heal 70% of max HP (current game value).
  - Events: no-op (sim doesn't model dialog choices).
- **Runs per cell:** ${opts.runs}

## Headline numbers

${opts.headline}

## Per-cell breakdown

${opts.perCell}

## Root cause hypothesis · recommendation · fix decision

See the hand-authored companion: [\`rogue-balance-analysis.md\`](./rogue-balance-analysis.md). The sim regenerates this file on every run, so analysis lives next door instead of being appended below.
`;
}
